//! Stream topology shapes and connection points.

mod bidi_shape;
mod closed_shape;
mod fan_in_shape10;
mod fan_in_shape11;
mod fan_in_shape12;
mod fan_in_shape13;
mod fan_in_shape14;
mod fan_in_shape15;
mod fan_in_shape16;
mod fan_in_shape17;
mod fan_in_shape18;
mod fan_in_shape19;
mod fan_in_shape2;
mod fan_in_shape20;
mod fan_in_shape21;
mod fan_in_shape22;
mod fan_in_shape3;
mod fan_in_shape4;
mod fan_in_shape5;
mod fan_in_shape6;
mod fan_in_shape7;
mod fan_in_shape8;
mod fan_in_shape9;
mod fan_out_shape2;
mod flow_shape;
mod inlet;
mod outlet;
mod port_id;
#[allow(clippy::module_inception)]
mod shape;
mod sink_shape;
mod source_shape;
mod stream_shape;
mod uniform_fan_in_shape;
mod uniform_fan_out_shape;

pub use bidi_shape::BidiShape;
pub use closed_shape::ClosedShape;
pub use fan_in_shape2::FanInShape2;
pub use fan_in_shape3::FanInShape3;
pub use fan_in_shape4::FanInShape4;
pub use fan_in_shape5::FanInShape5;
pub use fan_in_shape6::FanInShape6;
pub use fan_in_shape7::FanInShape7;
pub use fan_in_shape8::FanInShape8;
pub use fan_in_shape9::FanInShape9;
pub use fan_in_shape10::FanInShape10;
pub use fan_in_shape11::FanInShape11;
pub use fan_in_shape12::FanInShape12;
pub use fan_in_shape13::FanInShape13;
pub use fan_in_shape14::FanInShape14;
pub use fan_in_shape15::FanInShape15;
pub use fan_in_shape16::FanInShape16;
pub use fan_in_shape17::FanInShape17;
pub use fan_in_shape18::FanInShape18;
pub use fan_in_shape19::FanInShape19;
pub use fan_in_shape20::FanInShape20;
pub use fan_in_shape21::FanInShape21;
pub use fan_in_shape22::FanInShape22;
pub use fan_out_shape2::FanOutShape2;
pub use flow_shape::FlowShape;
pub use inlet::Inlet;
pub use outlet::Outlet;
pub use port_id::PortId;
pub use shape::Shape;
pub use sink_shape::SinkShape;
pub use source_shape::SourceShape;
pub use stream_shape::StreamShape;
pub use uniform_fan_in_shape::UniformFanInShape;
pub use uniform_fan_out_shape::UniformFanOutShape;
