//! Dispatcher module aligned with Apache Pekko's `MessageDispatcher` model.

mod balancing_dispatcher;
mod balancing_dispatcher_factory;
mod default_dispatcher;
mod default_dispatcher_factory;
mod dispatcher_config;
mod dispatcher_core;
mod dispatcher_sender;
mod dispatchers;
mod dispatchers_error;
mod drive_guard_token;
mod execute_error;
mod executor;
mod executor_factory;
mod executor_shared;
mod inline_executor;
mod message_dispatcher;
mod message_dispatcher_factory;
mod message_dispatcher_shared;
mod pinned_dispatcher;
mod pinned_dispatcher_factory;
mod shared_message_queue;
mod shutdown_schedule;
mod trampoline_state;

pub use balancing_dispatcher::BalancingDispatcher;
pub use balancing_dispatcher_factory::BalancingDispatcherFactory;
pub use default_dispatcher::DefaultDispatcher;
pub use default_dispatcher_factory::DefaultDispatcherFactory;
pub use dispatcher_config::DispatcherConfig;
pub use dispatcher_core::DispatcherCore;
pub use dispatcher_sender::DispatcherSender;
pub use dispatchers::{DEFAULT_BLOCKING_DISPATCHER_ID, DEFAULT_DISPATCHER_ID, Dispatchers};
pub use dispatchers_error::DispatchersError;
pub use execute_error::ExecuteError;
pub use executor::Executor;
pub use executor_factory::ExecutorFactory;
pub use executor_shared::ExecutorShared;
pub use inline_executor::InlineExecutor;
pub use message_dispatcher::MessageDispatcher;
pub use message_dispatcher_factory::MessageDispatcherFactory;
pub use message_dispatcher_shared::MessageDispatcherShared;
pub use pinned_dispatcher::PinnedDispatcher;
pub use pinned_dispatcher_factory::PinnedDispatcherFactory;
pub use shared_message_queue::SharedMessageQueue;
pub use shutdown_schedule::ShutdownSchedule;
pub use trampoline_state::TrampolineState;
