//! Outcome generated by membership coordinator processing.

use alloc::vec::Vec;

use crate::core::{ClusterEvent, GossipOutbound, MembershipEvent, QuarantineEvent};

/// Result of processing membership coordinator input.
#[derive(Debug, Default)]
pub struct MembershipCoordinatorOutcome {
  /// Optional topology event to publish.
  pub topology_event:    Option<ClusterEvent>,
  /// Member status events to publish.
  pub member_events:     Vec<ClusterEvent>,
  /// Gossip payloads to send.
  pub gossip_outbound:   Vec<GossipOutbound>,
  /// Internal membership events.
  pub membership_events: Vec<MembershipEvent>,
  /// Quarantine events to apply.
  pub quarantine_events: Vec<QuarantineEvent>,
}
